<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE tierra[
    <!ELEMENT continente (#PCDATA)>
    <!ELEMENT pais (#PCDATA)>
    <!ELEMENT capital (#PCDATA)>
    <!ELEMENT localizacion (continente,pais,capital)>
    <!ELEMENT tierra (localizacion*)>
]>
<tierra>
    <localizacion>
        <continente>Europa</continente>
        <pais>Alemania</pais>
        <capital>Berlin</capital>
    </localizacion>
    <localizacion>
        <continente>America</continente>
        <pais>Argentina</pais>
        <capital>Buenos Aires</capital>
    </localizacion>
    <localizacion>
        <continente>America</continente>
        <pais>Bahamas</pais>
        <capital>Nassau</capital>
    </localizacion>
    <localizacion>
        <continente>Asia</continente>
        <pais>Afganistan</pais>
        <capital>Kabul</capital>
    </localizacion>
    <localizacion>
        <continente>Asia</continente>
        <pais>Arabia Saudita</pais>
        <capital>Riad</capital>
    </localizacion>
</tierra>

