<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE internet[
    <!ELEMENT descripcion (#PCDATA)>
    <!ELEMENT dia (#PCDATA)>
    <!ELEMENT mes (#PCDATA)>
    <!ELEMENT anyo (#PCDATA)>
    <!ELEMENT fecha (dia,mes,anyo)>
    <!ELEMENT hechoHistorico (descripcion,fecha)>
    <!ELEMENT internet (hechoHistorico*)>
]>
<internet>
	<hechoHistorico>
		<descripcion> Se Funda Youtube</descripcion>
		<fecha>
			<dia>15</dia>
			<mes>02</mes>
			<anyo>2005</anyo>
		</fecha>
	</hechoHistorico>
	<hechoHistorico>
		<descripcion>Se funda Google</descripcion>
		<fecha>
			<dia>04</dia>
			<mes>09</mes>
			<anyo>1998</anyo>
		</fecha>
	</hechoHistorico>
	<hechoHistorico>
		<descripcion> Se Funda Facebook</descripcion>
		<fecha>
			<dia>04</dia>
			<mes>02</mes>
			<anyo>2004</anyo>
		</fecha>
	</hechoHistorico>
	
</internet>