=== davidas02/2021_LMSGI_DAS/2021_lmsgi_das/ud04/modeloComplejo.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
            <xs:element name="modelo">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="curso">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                  <xs:minInclusive value="1"/>
                                  <xs:maxInclusive value="2"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="ciclo">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                  <xs:enumeration value="DAW"/>
                                  <xs:enumeration value="SMR"/>
                                  <xs:enumeration value="ASIR"/>
                                  <xs:enumeration value="DAM"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="nombreA">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:minLength value="3"/>
                                    <xs:maxLength value="100"/>
                                    <xs:pattern value="[A-ZÑ]([a-zA-ZñÑ ])*"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="codigoPostal">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="[0-9][0-9][0-9][0-9][0-9]"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="comentario">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:whiteSpace value="collapse"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="temperatura">
                            <xs:simpleType>
                                <xs:restriction base="xs:decimal">
                                    <xs:totalDigits value="5"/>
                                    <xs:fractionDigits value="2"/>
                                    <xs:minInclusive value="-30"/>
                                  <xs:maxInclusive value="50"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="codA">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="EDD|LMSGI|SIF|FOL|BBDD|PROG"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="profesor">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <xs:attribute name="codP">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                            </xs:simpleType>
                                        </xs:attribute>
                                            
                                         
                                        <xs:attribute name="modulo" type="xs:string"/> 
                                        
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
</xs:schema>

=== davidas02/2021_LMSGI_DAS/2021_lmsgi_das/ud04/modeloComplejo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<modelo
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='modeloComplejo.xsd'>
    <curso>1</curso>
    <ciclo>DAW</ciclo>
    <nombreA>Desarrollo de Aplicaciones Web</nombreA>
    <codigoPostal>49600</codigoPostal>
    <comentario>Este  ciclo  tiene una insercion  laboral de 100%</comentario>
    <temperatura>32.2</temperatura>
    <codA>EDD</codA>
    <profesor codP="ARN" modulo="LMSGI">
    Amor Rodriguez
    </profesor>
</modelo>
