=== davidas02/2021_LMSGI_DAS/2021_lmsgi_das/ud04/receta/receta.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT recetas (receta)*>
<!ATTLIST recetas
    version CDATA #IMPLIED
    elementFormDefault CDATA #IMPLIED
    xmlns:xs CDATA #IMPLIED
  >
<!ELEMENT receta (nombre+,descripcion*,tiempo+,ingredientes+,instrucciones?)>
<!ATTLIST receta plato (primero|segundo|postre) #REQUIRED>
<!ELEMENT nombre (#PCDATA) >
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT tiempo (#PCDATA)>
<!ATTLIST tiempo preparacion CDATA #REQUIRED>
<!ATTLIST tiempo coccion CDATA #IMPLIED>
<!ELEMENT ingredientes (ingrediente*)>
<!ELEMENT ingrediente (nombreI,cantidad)>
<!ELEMENT nombreI (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ATTLIST cantidad medida (gramos|pizca|mililitros|cucharada|chorro) #REQUIRED>
<!ELEMENT instrucciones (paso+)>
<!ELEMENT paso (#PCDATA)>

=== davidas02/2021_LMSGI_DAS/2021_lmsgi_das/ud04/receta/receta.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE recetas SYSTEM 'receta.dtd'>
<recetas>
    <receta plato="primero">
        <nombre>
            Rissoto milanesa
        </nombre>
        <descripcion>
        
        </descripcion>
        <tiempo coccion="minutos">
            20
        </tiempo>
        <tiempo preparacion="minutos">
            40
        </tiempo>
        <ingredientes>
            <ingrediente>
                <nombreI>
                    arroz
                </nombreI>
                <cantidad unidad="gramos">
                    500
                </cantidad>
            </ingrediente>
            <ingrediente>
                <nombreI>
                    cebolla
                </nombreI>
                <cantidad>
                    1 mediana
                </cantidad>
            </ingrediente>
            <ingrediente>
                <nombreI>
                    azafran
                </nombreI>
                <cantidad unidad="pizca">
                    1
                </cantidad>
            </ingrediente>
            <ingrediente>
                <nombreI>
                    queso parmesano
                </nombreI>
                <cantidad unidad="gramos">
                    100
                </cantidad>
            </ingrediente>
            <ingrediente>
                <nombreI>
                    mantequilla
                </nombreI>
                <cantidad unidad="gramos">
                    100
                </cantidad>
            </ingrediente>
            <ingrediente>
                <nombreI>
                    Sal
                </nombreI>
            </ingrediente>
            <ingrediente>
                <nombreI>
                    Pimienta
                </nombreI>
            </ingrediente>
            <ingrediente>
                <nombreI>
                    caldo
                </nombreI>
                <cantidad unidad="mililitros">
                    1000 
                </cantidad>
            </ingrediente>
            <ingrediente>
                <nombreI>
                    vino blanco
                </nombreI>
                <cantidad unidad="chorro">
                    1
                </cantidad>
            </ingrediente>
        </ingredientes>
        <instrucciones>
            <paso>
                Paso 1- Picamos la cebolla y la pochamos con la mitad de la mantequilla.
            </paso>
            <paso>
                Paso2- Cuando esté transparente, echamos el azafrán, el vino y dejamos que reduzca.
            </paso>
            <paso>
                Paso 3.- A continuación, incorporamos el arroz, losofreímos un poco. 
            </paso>
            <paso>
                Paso 4.- Vamos añadiendo el caldo caliente poco a poco mientras removemos.
            </paso>
            <paso>
                Paso 5.- Salpimentamos.
            </paso>
            <paso>
                Paso 6.- Cuando esté casi hecho, agregamos el resto de la mantequilla y el queso.
            </paso>
            <paso>
                Paso 7.- Servimos enseguida.
            </paso>
        </instrucciones>
    </receta>
</recetas>
