<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE mail[
    <!ELEMENT remitente (#PCDATA)>
    <!ELEMENT destinatario (#PCDATA)>
    <!ELEMENT dia (#PCDATA)>
    <!ELEMENT mes (#PCDATA)>
    <!ELEMENT anyo (#PCDATA)>
    <!ELEMENT asunto (#PCDATA)>
    <!ELEMENT mensaje (#PCDATA)>
    <!ELEMENT nombreFichero (#PCDATA)>
    <!ELEMENT tipoMIME (#PCDATA)>
    <!ELEMENT fecha (dia,mes,anyo)>
    <!ELEMENT ficherosAdjuntos (nombreFichero,tipoMIME)>
    <!ELEMENT mail (remitente,destinatario+,fecha,asunto?,mensaje?,ficherosAdjuntos*)>
]>
<mail>
	<remitente>diego.casfre@educa.jcyl.es</remitente>
	<destinatario>david.apasir@educa.jcyl.es</destinatario>
        <destinatario>aroa.graoma@educa.jcyl.es</destinatario>
	<fecha>
            <dia>26</dia>
            <mes>01</mes>
            <anyo>2021</anyo>
        </fecha>
	<asunto>Prueba</asunto>
	<mensaje/>
	<ficherosAdjuntos>
		<nombreFichero>prueba.pdf</nombreFichero>
		<tipoMIME>application/pdf</tipoMIME>
	</ficherosAdjuntos>
        <ficherosAdjuntos>
            <nombreFichero>prueba.jpg</nombreFichero>
            <tipoMIME>image/jpeg</tipoMIME>
        </ficherosAdjuntos>
</mail>